print('Tive que fazer outro python porque tem muitos exercícios KKKKKKK\nA proposta agora é criar uma tabuada.\nVamos lá!')
nome = input('Digite seu nome, para que possamos ficar mais pessoais rsrsrsrsrs: ')
n1 = float(input('Perfeito {}! Agora digite um número, e darei sua tabuada: '.format(nome)))
print('Mãos à massa!\nA primeira é: {:.0f}x1={:.0f}'.format(n1, n1*1))
print('Agora eu peguei o ritmo hehe. A segunda tabuada é: {:.0f}x2={:.0f}'.format(n1, n1*2))
(print('Vou parar de ficar digitando tanto: {:.0f}x3={:.0f}'.format(n1, n1*3)))
n4 = n1*4
n5 = n1*5
n6 = n1*6
print('Vou resumir:',n1,'x4=', n4)
print('Ficou melhor: {:.0f}x5={:.0f}'.format(n1, n5))
print('GG:{}x6={}'.format(n1, n6))
n7 = 7
n8 = 8
n9 = 9
n10 = 10
print('A tabuada de {:.0f}x{:.0f}={:.0f}'.format(n1, n7, n1*n7))
print('A tabuada de {:.0f}x{:.0f}={:.0f}'.format(n1, n8, n1*n8))
print('A tabuada de {:.0f}x{:.0f}={:.0f}'.format(n1, n9, n1*n9))
print('A \ntabuada\n de {:.0f}x{:.0f}={:.0f}'.format(n1, n10, n1*n10))