print('DESAFIO DAS LATAS DE TINTAS!!!')
print('v'*20)
print()
la = float(input('Digite aqui a largura de sua parede(em m2): '))
al = float(input('Ótimo, agora me diga a altura desta parede(em m2): '))
ar = (al*la)
print()
print('^'*20)
print('Perfeito! Agora vamos descobrir quantas latas de tinta você precisará. ')
ti = float(input('Digite aqui quantos metros quadrados você pintará com uma lata(dependendo do tamanho da mesma): '))
print()
to = (ar/ti)
print('Tudo pronto! A área de sua parede é {}m2.\nE você irá precisar de {:.1f} latas de tinta para pinta-la por completo.'.format(ar, to))
