print('MELHOR IRMOS DORMIR, ESTOU MORRENDO DE SONO!')
print('HOJE FOI UM DIA PRODUTIVO, PORÉM NÃO SINTO POTENCIAL')
print()
print()
tt = input('Por favor, só me diga seu nome: ')
print('Ok {}. Boa noite, nao aguento mais...'.format(tt))
