print('ALUGUEL DE CARROS!!!')
print()
print('*'*20)
print()
print('Bem vindo ao ALUGA CARS! Para sua comodidade, siga as instruções abaixo para calcular o valor de seu aluguel:')
print()
di = int(input('Quantos dias o carro ficou/ficará alugado? '))
km = float(input('E quantos quilômetros foram/serão rodados? '))
print()
v1 = 20
v2 = 2
print('Agora digite os valores referentes a :')
print()
vd = float(input('Diária do carro: R$ '))
vk = float(input('Valor por KM: R$ '))
to = (vd*di)+(km*vk)
print()
print('Obrigada! O valor total de sua locação é: R${:=^10.2f}'.format(to))
print()
print('*'*20)
