print('CÁLCULO DE DESCONTOS EM PRODUTOS OU SERVIÇOS! ')
print()
print('*'*20)
print()
print('Bem vindo a nossa loja, este é o aplitaivo DESCONTA MAIS!\nPara saber o preço final, siga as instruções abaixo: ')
print()
pd = float(input('Por favor, digite aqui o valor do produto sem desconto: R$ '))
ds = float(input('Ótimo ! Agora, digite qual o desconto fornecido individualmente para você: % '))
fi = (pd*((100-ds)/100))
print()
print('Parabéns, e obrigado por escolher nossa loja! O valor final de seu produto é R${:=^20.2f}'.format(fi))
de = (pd-fi)
print('Seu desconto foi de R$ {:.2f}'.format(de))
