print('CONVERSÃO DE MOEDAS! ')
print('v'*50)
print()
n1 = float(input('Digite aqui o valor que você comprará em BTC: R$ '))
n2 = float(input('Agora, digite a cotação atual da cripto: '))
print()
btc = (n1/n2)
print('*'*10)
print()
print('Parabéns por trocar seus R$ {:.0f} fiduciários por uma moeda de verdade.\nSeu montante em BTC será igual a {:.4f}...'.format(n1, btc))
print()
print('*'*10)
